name: Frontend CD
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  NODE_VERSION: '20.x'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          
      - name: Install Dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        run: cd starter/frontend && npm run lint -- --fix
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install Dependencies
        working-directory: starter/frontend
        run: npm ci
    
      - name: Run tests
        run: cd starter/frontend && npm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps: 

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{ secrets.AWS_REGION}}
        
    - name: Logging into ECR
      uses: aws-actions/amazon-ecr-login@v2
  
    - name: Build and Push Docker Image
      working-directory: starter/frontend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http:/ad32ea29140aa4140a9d715936d25a3f-455093354.us-east-1.elb.amazonaws.com --tag=frontend:${GITHUB_SHA} .
        docker tag frontend:${GITHUB_SHA} 505370451601.dkr.ecr.us-east-1.amazonaws.com/frontend:${GITHUB_SHA}
        docker push 505370451601.dkr.ecr.us-east-1.amazonaws.com/frontend:${GITHUB_SHA}
    
    - name: Configuring Kubeconfig
      run:
       aws eks update-kubeconfig --name cluster --region us-east-1


    - name: Update kimage
      run: |
        cd ./starter/frontend/k8s && kustomize edit set image frontend=505370451601.dkr.ecr.us-east-1.amazonaws.com/frontend:${GITHUB_SHA}

    - name: Apply kubectl
      run: |
        cd starter/frontend/k8s && kustomize build | kubectl apply -f -
        kubectl get svc -A

    
